<?php


class EImageVinile extends EImage
{
  private $idVin;

  public function __construct($fname, $data, $type,$id)
  {
      parent::__construct($fname, $data, $type);
      $this->idVin=$id;
  }


    /**
     * @return mixed
     */
    public function getIdVin()
    {
        return $this->idVin;
    }

    /**
     * @param mixed $idVin
     */
    public function setIdVin($idVin): void
    {
        $this->idVin = $idVin;
    }

    public function __toString()
    {
        $str="Id_Vinile: ".$this->getIdVin();
        $str =  parent::__toString(); // TODO: Change the autogenerated stub
        return $str;
    }


}