<?php

/**
 * Entità Immagine Utente (immagine degli utenti iscritti nel sito), dove sono presenti
 * le caratteristiche di specifica e i suoi metodi peculiari, ereditando anche dalla classe padre.
 * Essa, infatti, rappresenta una classe figlio dell'interfaccia.
 * @author Gruppo Cruciani - Nanni - Scarselli
 * @package Entity
 */

class EImageUtente extends EImage
{
   private $emailUtente;

   //-------------------------COSTRUTTORE-------------------------

    /**
     * EImageUtente constructor.
     * @param $fname
     * @param $data
     * @param $type
     * @param $emailUtente
     */

    public function __construct($fname, $data, $type,$mail)
    {
        parent::__construct($fname, $data, $type);
        $this->emailUtente=$mail;
    }

    /**
     * Metodo che ci permette di prendere l'email dell'utente.
     * @return mixed
     */

    public function getEmailUtente()
    {
        return $this->emailUtente;
    }

    /**
     * Metodo che ci permette di cambiare l'email dell'utente.
     * @param mixed $emailUtente
     */

    public function setEmailUtente ($emailUtente): void
    {
        $this->emailUtente = $emailUtente;
    }

    /**
     * Metodo che ci permette di stampare a video tutti i dati dell'immagine.
     * @return string
     */

    public function __toString()
    {
        $str = "EmailUtente: ".$this->getEmailUtente();
        $str=$str.parent::__toString(); // TODO: Change the autogenerated stub
        return $str;
    }

}