<?php


class EImageUtente extends EImage
{
   private $emailUtente;

    /**
     * EImageUtente constructor.
     * @param $fname
     * @param $email
     */
     function __construct($fname,string $email)
   {
       parent::__construct($fname);
       $this->emailUtente=$email;
   }

    /**
     * @return mixed
     */
    public function getEmailUtente()
    {
        return $this->emailUtente;
    }

    /**
     * @param mixed $emailUtente
     */
    public function setEmailUtente($emailUtente): void
    {
        $this->emailUtente = $emailUtente;
    }

    public function __toString()
    {
        $str = "EmailUtente: ".$this->getEmailUtente();
        $str=$str.parent::__toString(); // TODO: Change the autogenerated stub
        return str;
    }


}