<?php


class EImageUtente extends EImage
{
   private $emailUtente;

    /**
     * EImageUtente constructor.
     * @param $fname
     * @param $email
     */
    public function __construct($fname, $data, $type,$mail)
    {
        parent::__construct($fname, $data, $type);
        $this->emailUtente=$mail;
    }

    /**
     * @return mixed
     */
    public function getEmailUtente()
    {
        return $this->emailUtente;
    }

    /**
     * @param mixed $emailUtente
     */
    public function setEmailUtente ($emailUtente): void
    {
        $this->emailUtente = $emailUtente;
    }

    public function __toString()
    {
        $str = "EmailUtente: ".$this->getEmailUtente();
        $str=$str.parent::__toString(); // TODO: Change the autogenerated stub
        return $str;
    }


}