<?php


class ENegozio extends EUtente_loggato{
     /** email è identificativo e fa riferimento a email della classe padre*/
     private $email_negozio;
     private $nameShop;
     private $p_iva;
     private $address;
     private $carta;
     private $abbonamento;

     /** Questo metodo è il costruttore della classe ENegozio.
     * ENegozio constructor.
     * @param string $nomeNegozio
     * @param string $iva
     * @param string $indirizzo
      * @param ECarta $carta
      * @param EAbbonamento $abb
     */
       public function __construct($name, $mail, $pw, $tel, $stato, $datareg,$nomeNegozio,$iva,$indirizzo,ECarta $cart,EAbbonamento $abb)
       {
           parent::__construct($name, $mail, $pw, $tel, $stato, $datareg);
           $this->nameShop=$nomeNegozio;
           $this->p_iva=$iva;
           $this->address=$indirizzo;
           $this->carta=new Ecarta($cart->getIntestat(),$cart->getNum(),$cart->getScad(),$cart->getCodcvv());
           $this->abbonamento=new EAbbonamento();
       }

       //METODI GET

    /** Questo metodo ritorna il nome del Negozio.
     * @return mixed
     */
    public function getNameShop()
    {
        return $this->nameShop;
    }

    /** Questo metodo ritorna la partita iva del Negozio
     * @return mixed
     */
    public function getPIva()
    {
        return $this->p_iva;
    }

    /** Questo metodo ritorna l'indirizzo del Negozio
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @return mixed
     */
    public function getAbbonamento()
    {
        return $this->abbonamento;
    }

    /**
     * @return mixed
     */
    public function getCarta()
    {
        return $this->carta;
    }

        //METODI SET

    /** Questo metodo setta il nome del Negozio
     * @param mixed $nameShop
     */
    public function setNameShop($nameShop)
    {
        $this->nameShop = $nameShop;
    }

    /** Questo metodo setta la partita iva del Negozio
     * @param mixed $p_iva
     */
    public function setPIva($p_iva)
    {
        $this->p_iva = $p_iva;
    }

    /** Questo metodo setta l'indirizzo del Negozio
     * @param mixed $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * @param EAbbonamento $abbonamento
     */
    public function setAbbonamento(EAbbonamento $abbonamento)
    {
        $x=$this->abbonamento = $abbonamento;
        return $x;
    }

    /**
     * @param Ecarta $carta
     */
    public function setCarta(Ecarta $carta)
    {
        $x=$this->carta = $carta;
        return $x;
    }

    //Metodo toString

    /** Metodo ToString che stampa tutte le informazioni del Negozio
     * @return string
     */
    public function toString()
    {
        return parent::toString(); // TODO: Change the autogenerated stub
        "Nome negozio: " . $this->nameShop . "\n";
        "Partita iva: " . $this->p_iva. "\n";
        "Indirizzo: " . $this->address->toString(). "\n";
        "Carta: ".$this->carta->toString()."\n";
        "Abbonamento: ".$this->abbonamento->toString()."\n";

    }

}