<?php


class ENegozio extends EUtente_loggato{
     // email è identificativo e fa riferimento a email della classe padre
     private $email_negozio;
     private $nameShop;
     private $p_iva;
     private $andress;

       public function __construct($name, $mail, $pw, $tel, $stato, $datareg,$nomeNegozio,$iva,$indirizzo)
       {
           parent::__construct($name, $mail, $pw, $tel, $stato, $datareg);
           $this->nameShop=$nomeNegozio;
           $this->p_iva=$iva;
           $this->andress=$indirizzo;
       }


       //METODI GET

    /**
     * @return mixed
     */
    public function getNameShop()
    {
        return $this->nameShop;
    }

    /**
     * @return mixed
     */
    public function getPIva()
    {
        return $this->p_iva;
    }

    /**
     * @return mixed
     */
    public function getAndress()
    {
        return $this->andress;
    }

        //METODI SET

    /**
     * @param mixed $nameShop
     */
    public function setNameShop($nameShop)
    {
        $this->nameShop = $nameShop;
    }

    /**
     * @param mixed $p_iva
     */
    public function setPIva($p_iva)
    {
        $this->p_iva = $p_iva;
    }

    /**
     * @param mixed $andress
     */
    public function setAndress($andress)
    {
        $this->andress = $andress;
    }

    //Metodo toString

    public function toString()
    {
        return parent::toString(); // TODO: Change the autogenerated stub
        "Nome negozio: " . $this->nameShop . "\n";
        "Partita iva: " . $this->p_iva. "\n";
        "Indirizzo: " . $this->andress. "\n";

    }






}